language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - platformio platform install file://./QIO/

script:
  - platformio run -s -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
