name: ubuntu

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions
# on:
#   push:
#     branches:
#       - master
#     tags:
#       - '[0-9]+.[0-9]+*'
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - master
#   schedule:
#     - cron: '0 3 * * *' # run every day at 3AM

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'OS-Q/P19'
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        examples:
          - "examples/arduino-blink"
          - "examples/arduino-internal-libs"
          - "examples/native-blink"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          python -m pip install --upgrade pip
          zip -r P19.zip boards builder link.json
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install P19.zip

      - name: Build
        run: |
          qio run -d ${{ matrix.examples }}

      - name: Package
        if: github.repository == 'OS-Q/P19'
        env:
          USERNAME: ${{ secrets.DEPLOY_USER }}
          HOSTNAME: ${{ secrets.DEPLOY_HOST }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        run: |
          sshpass -p $PASSWORD scp P19.zip $USERNAME@$HOSTNAME:/home/www/html/package &

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-upload
          path: P19.zip
