name: windows

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: windows-latest
    if: github.repository == 'OS-Q/P19'
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        examples:
          - "examples/arduino-blink"
          - "examples/arduino-internal-libs"
          - "examples/native-blink"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        run: |
          qio run -d ${{ matrix.examples }}

      - name: Clean
        if: github.repository == 'OS-Q/P19'
        run: |
          mkdir P19
          copy boards P19  –recurse
          copy builder P19  –recurse
          copy link.json P19

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: windows-upload
          path: P19

      - uses: actions/upload-artifact@v2
        with:
          name: windows-build-P11
          path: ${{ matrix.examples }}/build
